architecture: YOLOv3
#### 迁移学习 ####
# pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
pretrain_weights: 
# finetune_exclude_pretrained_params: 
#### 评价预测用权重 ####
weights: output/yolov3_darknet_insects/model_final
#### 训练过程 ####
# use_gpu: True
use_gpu: False
max_iters: 20000
log_iter: 20 # log窗口 
log_smooth_window: 20 # 训练过程指标平滑窗口  
snapshot_iter: 2000 # 评价窗口
save_dir: output # 训练过程中的模型保存目录
# metric: VOC
map_type: 11point
#### 全局参数 ####
num_classes: 7
use_fine_grained_loss: false
# weight_prefix_name: 
# norm_type: bn

YOLOv3:
  backbone: DarkNet
  # yolo_head: YOLOv3Head
  # use_fine_grained_loss: False #

ResNet:
  depth: 50
  variant: 'b'
  freeze_at: 2

  freeze_norm: True
  norm_type: 'affine_channel'
  norm_decay: 0.

  feature_maps: [2 3 4 5]

  dcn_v2_stages: []
  nonlocal_stages: []
  gcb_stages: []
  gcb_params: {}

  weight_prefix_name: ''

DarkNet:
  depth: 53
  # norm_type: bn #
  # norm_decay: 0.
  # weight_prefix_name: '' #

YOLOv3Head:
  # norm_decay: 0.
  # num_classes: 80 #
  anchors: [[19, 29], [28, 20], [25, 40], 
            [31, 47], [36, 37], [41, 26], 
            [47, 66], [48, 33], [67, 53]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  # drop_block: False
  # block_size: 3
  # keep_prob: 0.9
  # yolo_loss: YOLOv3Loss
  nms:
    score_threshold: 0.01
    nms_top_k: 1000
    # keep_top_k: 100
    nms_threshold: 0.45
    # normalized: false
    # nms_eta: 1.0
    background_label: -1
  # weight_prefix_name: ''  #

YOLOv3Loss:
  batch_size: 8
  # ignore_thresh: 0.7
  label_smooth: false
  # use_fine_grained_loss: False #
  # iou_loss: 

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 400000
    - 450000
    # values:
  - !LinearWarmup
    steps: 4000
    start_factor: 0.

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_darknet_insects_reader.yml'

